log:
  level: debug
  disable_sentry: true

db:
  url: postgres://postgres:12345@localhost:5432/linkShortenerDB

listener:
  addr: :8000

cop:
  disabled: true
  endpoint: "http://..."
  upstream: "http://..."
  service_name: link-shortener-svc
  service_port: 80
