openapi: 3.0.0
info:
  version: 1.0.0
  title: link-shortener-svc
  description: Link shortening service
servers:
  - url: 'https://localhost:8000/integrations'
    description: Link Shortener Developer Server
